### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by danichao** [brandonckelly/carma_pack#12]
Hi, 
I tried to install carma_pack on linux, and everything went successfully without any error. However, I fail to run python testCarmcmc.py. It gave the following message:

Traceback (most recent call last):
  File "testCarmcmc.py", line 4, in <module>
    import carmcmc 
  File "/afs/mpa/home/dchao/.conda/envs/my_root/lib/python2.7/site-packages/carmcmc/__init__.py", line 1, in <module>
    from _carmcmc import *
ImportError: /usr/lib64/libboost_python.so.1.61.0: undefined symbol: PyUnicodeUCS2_AsWideChar

Does it mean that the BOOST libraries were not built successfully?

Cheers,
Dani

**Comment by brandonckelly** [comment]
Hi Dani,

Yes, that would be my guess. I have never seen that build error before, but
it looks like a problem with building BoostPython.

Good luck!
-Brandon
